sito4.0/Controllers/LibriController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Web;
using System.Web.Mvc;

namespace MyWebApplication.Controllers
{
    [Authorize]
    public class LibriController : MyBaseController
    {


        public const int MaxWidthImage = 500;
        public const int MaxHeightImage = 500;

        public const int WidthThumbnail = 200;
        public const int HeightThumbnail = 200;

        private const string SESSSION_FILTER_SEARCH = "SearchLibriModel";

        private Annunci.Libri.LibriManager manager = new Annunci.Libri.LibriManager("mercatino");

        private MyManagerCSharp.RegioniProvinceComuniManager regioniProvinceComuniManager = new MyManagerCSharp.RegioniProvinceComuniManager("RegioniProvinceComuni");


        [AllowAnonymous]
        public ActionResult Index(Annunci.Libri.Models.SearchLibri model)
        {
            Debug.WriteLine("HttpMethod: " + (Request.HttpMethod == null ? "NULL" : Request.HttpMethod.ToString()));
            Debug.WriteLine("UrlReferrer: " + (Request.UrlReferrer == null || Request.UrlReferrer.LocalPath == null ? "NULL" : Request.UrlReferrer.LocalPath));

            if (Request.HttpMethod.ToString() == "GET" && Session[SESSSION_FILTER_SEARCH] != null && Request.UrlReferrer != null
                && Request.UrlReferrer.LocalPath.IndexOf("/Libri/TestiScolastici") == -1
                //&& Request.UrlReferrer.LocalPath.IndexOf("/Libri/Details") == -1
                && Request.UrlReferrer.LocalPath != "/Libri/Categorie")
            {
                model = (Session[SESSSION_FILTER_SEARCH] as Annunci.Libri.Models.SearchLibri);
                //model.filter = (Session[SESSSION_FILTER_SEARCH] as Annunci.Libri.Models.Libro);
                Debug.WriteLine("Leggo i parametri di ricerca dalla sessione ...");
                Debug.WriteLine("Filtro Days: " + model.days);
            }

            if (model.filter == null)
            {
                model.filter = new Annunci.Libri.Models.Libro();
            }
            Debug.WriteLine("collapseShow: " + model.collapseShow);
            Debug.WriteLine("CategoriaId: " + model.filter.categoriaId);
            Debug.WriteLine("SubCategoriaId: " + model.filter.subCategoriaId);

            System.Collections.Hashtable hashtablePhoto = new System.Collections.Hashtable();
            try
            {
                manager.mOpenConnection();

                model.comboCategorie = manager.getComboCategoria(1000000);
                if (model.filter.categoriaId != null &&
                    ((model.filter.categoriaId >= 1130000 && model.filter.categoriaId < 1140000) || (model.filter.categoriaId >= 1140000 && model.filter.categoriaId < 1150000)))
                {
                    model.comboSubCategorie = manager.getComboCategoria((int)model.filter.categoriaId);
                }

                model.comboRegioni = regioniProvinceComuniManager.getComboRegioni();
                if (model.filter.regioneId != null)
                {
                    model.comboProvince = regioniProvinceComuniManager.getComboProvince((int)model.filter.regioneId);
                }

                if (model.filter.provinciaId != null)
                {
                    model.comboComuni = regioniProvinceComuniManager.getComboComuni(model.filter.provinciaId);
                }

                manager.getList(model);


                long numeroPhoto;
                foreach (Annunci.Libri.Models.Libro i in model.Libri)
                {
                    numeroPhoto = manager.countPhoto(i.annuncioId);
                    hashtablePhoto.Add(i.annuncioId, numeroPhoto);
                }


                if (model.filter.categoriaId == 1130000 && model.filter.subCategoriaId == null)
                {
                    model.filter.categoria = "Testi scolastici";
                }

                if (model.filter.categoriaId == 1140000 && model.filter.subCategoriaId == null)
                {
                    model.filter.categoria = "Testi universitari";
                }

                /* 
                 //gestione nome categoria 
                 switch (model.filter.subCategoriaId)
                 {
                     case 1130100:
                         model.filter.categoria = "Testi scolastici elemetari";
                         break;
                     case 1130200:
                         model.filter.categoria = "Testi scolastici medie";
                         break;
                     case 1130300:
                         model.filter.categoria = "Testi scolastici superiori";
                         break;
                     case 1130400:
                         model.filter.categoria = "Testi scolastici altro";
                         break;
                 }

     */

            }
            finally
            {
                manager.mCloseConnection();
            }

            Session[SESSSION_FILTER_SEARCH] = model;
            ViewData["hashtablePhoto"] = hashtablePhoto;
            return View("Index", model);
        }


        [AllowAnonymous]
        public ActionResult Categorie()
        {
            return View();
        }


        [AllowAnonymous]
        public ActionResult Categoria(int? id)
        {
            Debug.WriteLine("HttpMethod: " + (Request.HttpMethod == null ? "NULL" : Request.HttpMethod.ToString()));
            Debug.WriteLine("UrlReferrer: " + (Request.UrlReferrer == null || Request.UrlReferrer.LocalPath == null ? "NULL" : Request.UrlReferrer.LocalPath));
            Debug.WriteLine("Categoria: " + id);

            Annunci.Libri.Models.SearchLibri model;
            model = (Session[SESSSION_FILTER_SEARCH] as Annunci.Libri.Models.SearchLibri);
            if (model == null)
            {
                model = new Annunci.Libri.Models.SearchLibri();
            }

            if (id != -1)
            {
                model.filter.categoriaId = id;

                if (id >= 1130000 && id < 1140000)
                {
                    model.filter.categoriaId = 1130000;
                    model.filter.subCategoriaId = id;
                }

                if (id >= 1140000 && id < 1150000)
                {
                    model.filter.categoriaId = 1140000;
                    model.filter.subCategoriaId = id;

                }
                /* rimosso nella rel.  3.0.0.8 - 30/04/2018
                if (Request.Browser.Browser.Contains("AdsBot-Google") || Request.Browser.Browser.Contains("Googlebot"))
                {
                    model.PageSize = 0;
                    model.PageNumber = 1;
                }
                */
            }
            Session[SESSSION_FILTER_SEARCH] = model;

            //return RedirectToAction("Index", model);
            return Index(model);
        }



        public ActionResult MyAnnunci(Annunci.Libri.Models.SearchLibri model)
        {
            System.Collections.Hashtable hashtableRisposte = new System.Collections.Hashtable();
            try
            {
                manager.mOpenConnection();

                manager.getMyListAnnunci(MySessionData.UserId, model);

                Annunci.AnnunciManager annuncioManager = new Annunci.AnnunciManager(manager.mGetConnection());
                long numeroRisposte;
                foreach (Annunci.Libri.Models.Libro i in model.Libri)
                {
                    numeroRisposte = annuncioManager.getNumeroRisposteOfAnnuncio(i.annuncioId, MySessionData.UserId);
                    hashtableRisposte.Add(i.annuncioId, numeroRisposte);
                }
            }
            finally
            {
                manager.mCloseConnection();
            }

            ViewData["hashtableRisposte"] = hashtableRisposte;
            return View(model);
        }

        public ActionResult MyTrattative()
        {
            manager.mOpenConnection();

            List<Annunci.Models.Trattativa> risultato;

            try
            {
                risultato = manager.getListTrattative(MySessionData.UserId, Annunci.Models.Trattativa.TipoTrattativa.Libro);
            }
            finally
            {
                manager.mCloseConnection();
            }


            return View(risultato);
        }


        [Authorize]
        public ActionResult Trattativa(long? id)
        {
            Debug.WriteLine("trattativaId: " + id);
            Models.ModelTrattativa model = new Models.ModelTrattativa();

            manager.mOpenConnection();
            try
            {
                //La coppa trattativaID e annuncioID sono + sicuri per leggere gli annunci
                //if (annuncioId == null) {
                //  annuncioId = manager.getAnnucioIdFromTrattativa((long)trattativaId);
                //}

                model.trattativa = manager.getTrattativa((long)id);
                if (model.trattativa == null)
                {
                    return View("~/Views/Errors/NotAvailable.cshtml");
                }

                if (!manager.authorizeShowTrattativa(MySessionData.UserId, (long)id))
                {
                    return RedirectToAction("NotAuthorized", "Errors");
                }


                manager.setRisposteFromTrattativa(model.trattativa);


                model.libro = manager.getLibro(model.trattativa.annuncioId);
                if (model.libro == null)
                {
                    //vuol dire che l'annuncio è stato rimosso ... 
                    //return View("NotAvailable");

                    // il controllo lo faccio sulla VIEW così visualizzo i pulsanti corretti
                }


                //Verifico se l'utente che ha inserito la risposta sia il prorietario dell'annuncio
                bool isOwner;
                isOwner = manager.isOwner(model.trattativa.annuncioId, MySessionData.UserId);

                if (isOwner)
                {

sito4.0/Controllers/RegioneProvinciaComuneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;

namespace MyWebApplication.Controllers
{
    public class RegioneProvinciaComuneController : Controller
    {
        //
        // GET: /RegioneProvinciaComune/

        public ActionResult Index()
        {
            return View();
        }




        public ActionResult GetProvince(long? regioneId)
        {
            if (regioneId == null)
            {
                //return Json(null, JsonRequestBehavior.AllowGet);
                List<MyManagerCSharp.Models.MyItem> risultato = new List<MyManagerCSharp.Models.MyItem>();
                return Json(risultato, JsonRequestBehavior.AllowGet);
            }


            MyManagerCSharp.RegioniProvinceComuniManager m = new MyManagerCSharp.RegioniProvinceComuniManager("RegioniProvinceComuni");
            m.mOpenConnection();

            System.Data.DataTable dt = null;

            try
            {

                //  regioneId = int.Parse (m.getRegioneByLabel(regione).Rows[0]["id"].ToString()) ; 

                dt = m.getProvince((long)regioneId);
            }
            finally
            {
                m.mCloseConnection();
            }

            return Json(dt.AsEnumerable().Select(x => new { value = x.Field<string>("Id"), text = x.Field<string>("valore") }), JsonRequestBehavior.AllowGet);

            //return Json(Enumerable.Range(1, 12).Select(x => new { value = x, text = x }),  JsonRequestBehavior.AllowGet );
        }


        public ActionResult GetComuni(string provinciaId)
        {
            MyManagerCSharp.RegioniProvinceComuniManager m = new MyManagerCSharp.RegioniProvinceComuniManager("RegioniProvinceComuni");
            m.mOpenConnection();

            System.Data.DataTable dt = null;

            try
            {


                dt = m.getComuni(provinciaId);
            }
            finally
            {
                m.mCloseConnection();
            }

            return Json(dt.AsEnumerable().Select(x => new { value = x.Field<string>("Id"), text = x.Field<string>("valore") }), JsonRequestBehavior.AllowGet);

        }
    }
}

sito4.0/Views/Shared/GalleryEdit.cshtml
@model MyWebApplication.Models.GalleryModel

@{
    System.IO.FileInfo fi;
    string temp;
    int conta = 0;
}

<button type="button" class="btn btn-info" onclick="javascript:MyAsyncUpdate();">Aggiorna</button>


<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#MyPopupDialog">
    Aggiungi una photo <i class="fa fa-plus fa-fw"></i>
</button>


<br />
<div id="MyGalleryEdit">
    <table class="table table-bordered mt-3 table-responsive">
        <tbody>

            @foreach (Annunci.Models.MyPhoto p in Model.photos)
            {
                conta++;
                System.Diagnostics.Debug.WriteLine("Path : " + Server.MapPath(p.Path));

                if (p.Path.StartsWith("http:"))
                {
                    <tr>
                        <td class="align-middle">@conta</td>
                        <td class="align-middle" style="width:10em">
                            <button class="btn btn-warning" disabled>Delete <i class="fa fa-trash"></i></button>
                        </td>
                        <td>
                            <a href="@p.Path" data-lightbox="gallery">
                                <img src="@p.Path" alt="@p.Note" />
                            </a>
                        </td>

                    </tr>

                }
                else
                {
                    fi = new System.IO.FileInfo(Server.MapPath(p.Path));
                    if (fi.Exists)
                    {
                        //verifico che ci sia la thumbnail
                        if (System.IO.File.Exists(fi.DirectoryName + System.IO.Path.DirectorySeparatorChar + "thumbnail_" + fi.Name))
                        {
                            temp = p.Path.Replace(fi.Name, "thumbnail_" + fi.Name);
                        }
                        else
                        {
                            temp = p.Path;
                        }

                        <tr>
                            <td class="align-middle">@conta</td>
                            <td class="align-middle" style="width:10em">
                                <button class="btn btn-warning" onclick="javascript:MyDeleteAsyncPopup('@p.PhotoId')">Delete <i class="fa fa-trash"></i></button>
                            </td>
                            <td>
                                <a href="@Url.Content(p.Path)" data-lightbox="gallery">
                                    <img src="@Url.Content(temp)" alt="@p.Note" />
                                </a>
                            </td>

                        </tr>
                    }
                    else
                    {
                        <tr>
                            <td class="align-middle">@conta</td>
                            <td class="align-middle" style="width:10em">
                                <button class="btn btn-warning" onclick="javascript:MyDeleteAsyncPopup('@p.PhotoId')">Delete <i class="fa fa-trash"></i></button>
                            </td>
                            <td>
                                <a href="#">
                                    <img src="@Url.Content("~/Content/Images/Shared/unavailable.jpg")" alt="Immagine non disponibile" width="120" height="120" />
                                </a>
                            </td>

                        </tr>
                    }
                }
            }

        </tbody>
    </table>
</div>






<!-- Modal -->
<div class="modal fade" id="MyPopupDialog" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Aggiungi una photo</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h3>Selezionale un'immagine</h3>
                @using (Html.BeginForm("AddImage", "Libri", FormMethod.Post, new { id = "MyFormUpload", enctype = "multipart/form-data" }))
                {
                    <input type="file" name="MyFile" id="MyFile" value="">

                    <input type="hidden" name="annuncioId" value="@Model.externalId" />

                    <span style="color: red; visibility: hidden;" id="MyResponseMessage">messaggio</span>
                    <br />

                    <div id="percent">0%</div>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annulla</button>
                <button type="button" class="btn btn-primary" onclick="javascript: MyAsyncUpload()">Upload</button>
            </div>
        </div>
    </div>
</div>

<input type="hidden" id="imageToBeDeleted" value="" />


@{ Html.RenderPartial("_ConfirmPopup", new ViewDataDictionary { { "ID", "confirmDeletePhoto" }, { "title", "Cancellazione immangine" } }); }



<script src="@Url.Content("~/Content/js/jquery.form-3.51.js")"></script>

<script type="text/javascript">

    $(document).ready(function () {
        $('#MyPopupDialog').on('hidden.bs.modal', function (e) {
            MyAsyncUpdate();
        })

    });

    function MyDeleteAsyncPopup(id) {
        console.log("MyDeleteAsyncPopup" + id);
        $("#imageToBeDeleted").val(id);
        $("#confirmDeletePhoto").modal('show');
    }



    function confirmDeletePhotoConfirmOnClick(){
        console.log("confirmDeletePhotoConfirmOnClick");
        $("#confirmDeletePhoto").modal('hide');
        let id = $("#imageToBeDeleted").val();
        MyDeleteAsync(id);
    }



    function MyDeleteAsync(id) {
        console.log("MyDeleteAsync: " + id);

        $.post("@(Url.Action("DeleteImage","Libri") + "/")" + id,
             function (data) {
                 //alert("data: " + data.esito);

                 if (data.esito == "Success") {
                     MyAsyncUpdate();
                 }
             });
    }


    function MyAsyncUpload() {
        console.log("MyAsyncUpload");

        //var MyData = $('#MyFormUpload').serialize();

        //alert("MyAsyncUpload");
        //var MyData = new FormData($('#MyFormUpload'));





        @*  $.ajax({
            url: "@Url.Action("AddImage", "Immobiliare")",
            type: "POST",
            data: MyData,
            beforeSend: function (xhr) {
                //xhr.overrideMimeType("text/plain; charset=x-user-defined");
                alert("beforeSend");
            }
        }).done(function (data) {
            alert("Done: " + data);
        });*@


        var options = {
            beforeSend: function () {
                //alert("beforeSend");
                $("#MyResponseMessage").css('visibility', 'hidden');
            },
            uploadProgress: function (event, position, total, percentComplete) {
                $('#percent').html(percentComplete + "%");
            },
            success: function () {

            },
            complete: function (response) {
                //response text from the server.
                //alert("response " + response.responseText);
                var obj = JSON.parse(response.responseText);

                $("#MyFile").val("");
                $('#percent').html("0%");
                // alert("esito: " + obj.messaggio);

                if (obj.esito == "Failed") {
                    $("#MyResponseMessage").html(obj.messaggio);
                    $("#MyResponseMessage").css('visibility', 'visible');
                } else {

                    $("#MyPopupDialog").modal('hide');
                    //MyAsyncUpdate();
                }

            }
        };

        $('#MyFormUpload').ajaxForm(options);
        $('#MyFormUpload').submit();
    }




    function MyAsyncUpdate() {


        $.get('@Url.Action("MyAnnuncio", "Libri", new { id = Model.externalId })', function (data) {
            // alert("MyGalleryEdit" + data);
            console.log("MyAsyncUpdate: " + data);
            $('#MyGalleryEdit').html(data);
            // $('#MyGalleryEdit').trigger('create');
        });
    }




</script>

















<style>
    #Galleryy {
        background-color: transparent;
    }
        /*#photo table.photo {  background-color: transparent; }  */


        #Galleryy ul {
            list-style: none;
            display: block;
            margin: 0px;
            padding: 0px;
        }


            #Galleryy ul li {
                display: block;
                width: 300px;
                float: left;
                background-color: azure;
                margin: 10px;
            }


        #Galleryy div.photo {
            margin: 10px;
            padding: 5px;
            border: 1px solid Black;
            float: left;
        }
            /* #photo div.photo img {border: 1px solid Black;   }*/
            #Galleryy div.photo .descrizione {
                margin-top: 5px;
                padding: 3px;
                font-size: 10px;
                text-align: center;
                background-color: #E2EECD;
            }
</style>

sito4.0/Views/Shared/LoginPartialMobile.cshtml
@if (Request.IsAuthenticated && Session != null && Session["MySessionData"] != null)
{
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Manage", "Account")"><i class="fa fa-user fa-fw"></i>@User.Identity.Name</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("LogOff", "Account")">Log Off</a>
    </li>
    
}
else
{
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Register", "Account")">Registrazione</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Login", "Account")">Login</a>
    </li>

}

sito4.0/Views/Shared/NotAuthorized.cshtml
@{
    ViewBag.Title = "NotAuthorized";
    Layout = "~/Views/Shared/_MasterPageMobile.cshtml";
}

<h2>Not Authorized</h2>
<p>
    Attenzione si sta tentando di accedere ad una pagina il cui contenuto necessita
    di un'autorizzazione particolare.
</p>

<p>Se non ti sei ancora autenticato clicca <a href="@Url.Action("Login", "Account")">qui</a> per accedere alla maschera di login.</p>

sito4.0/Views/Shared/_ComboCategoria.cshtml
<script type="text/javascript">





    function comboCategoriaGetSelectedValue() {
        console.log("comboCategoriaGetSelectedValue");

        console.log("comboSubCategoria" + $("#comboSubCategoria").val());

        if ($("#comboSubCategoria").val() == "") {

        }
    }
    function setComboCategoria(value) {
        console.log("setComboCategoria: " + value);
        $("#comboCategoria").val(value);
        /*if (value > 1130000 && value < 1140000) {
            //Testi scolastici
            console.log("Testi scolastici")
            $("#comboCategoria").val(1130000);
            $("#comboSubCategoria").val(value);
        } else if (value > 1140000 && value < 1150000) {
            //Testi scolastici
            console.log("Testi universitari")
            $("#comboCategoria").val(1140000);
            $("#comboSubCategoria").val(value);

        } else {
            $("#comboCategoria").val(value);
        }*/

    }


    function setComboSubCategoria(value) {
        console.log("setComboSubCategoria: " + value);
        $("#comboSubCategoria").val(value);

    }


    function comboCategoriaOnChange(e) {
        console.log("comboCategoriaOnChange", e);
        //let selected = $(this).find("option:selected").val();
        let selectedValue = $(this).val();
        let selectedText = $(this).find(":selected").text();
        console.log("comboCategoriaOnChange selectedValue:" + selectedValue);

        
        $('#comboSubCategoria').empty();
        $('#comboSubCategoria').append($('<option />', { value: "", text: "---" }));
        $('#comboSubCategoria').val("").change();



        if (selectedValue === undefined || selectedValue === "") {
            $('#categoria').val("");
            return;
        }

        $('#categoria').val(selectedText);

        if (selectedValue > 1130000 && selectedValue < 1140000) {
            //Testi scolastici
            console.log("Testi scolastici")
        }

        if (selectedValue > 1140000 && selectedValue < 1150000) {
            //Testi scolastici
            console.log("Testi universitari")
        }

        $.getJSON('@Url.Action("GetSubCategoria", "Libri")', { categoriaId: selectedValue }, function (dati) {

            $.each(dati, function (index, item) {
                //console.log(item.Value)
                $('#comboSubCategoria').append($('<option />', { value: item.Value, text: item.Text }));
            });

        });
    }

    /*
    function comboSubCategoriaOnChange(e) {
        let selectedValue = $(this).val();
        let selectedText = $(this).find(":selected").text();
        //console.log("comboCategoriaOnChange selectedValue:" + selectedValue);


        
        if (selectedValue === undefined || selectedValue === "") {
            //$('#categoria').val("");
            return;
        }

        $('#categoria').val(selectedText);
    }*/
</script>

sito4.0/Views/Shared/_ComboRegioneProvinciaComune.cshtml
<script type="text/javascript">

    function comboRegioneOnChange(e) {
        //console.log("comboRegioneOnChange", e);
        //let selected = $(this).find("option:selected").val();
        let selectedValue = $(this).val();
        //var selectedText = $(this).find(":selected").text();
        console.log("comboRegioneOnChange selectedValue:" + selectedValue);

        $('#comboProvincia').empty();
        $('#comboProvincia').append($('<option />', { value: "", text: "---" }));
        $('#comboProvincia').val("").change();

      //  $('#comboComune').empty();
//        $('#comboComune').append($('<option />', { value: "", text: "---" }));
        //$('#comboComune').val("").change();

        if (selectedValue === "") {
            return;
        }


        $.getJSON('@Url.Action("GetProvince", "RegioneProvinciaComune")', { regioneId: selectedValue }, function (dati) {

            $.each(dati, function (index, item) {
                //console.log(item.Value)
                $('#comboProvincia').append($('<option />', { value: item.value, text: item.text }));
            });

        });
    }

    function comboProvinciaOnChange(e) {
        //console.log("comboProvinciaOnChange", e);
        
        let selectedValue = $(this).val();
        let selectedText = $(this).find(":selected").text();
        console.log("comboProvinciaOnChange selectedValue:" + selectedValue);
        console.log("comboProvinciaOnChange selectedText:" + selectedText);

        $('#comboComune').empty();
        $('#comboComune').append($('<option />', { value: "", text: "---" }));
        $('#comboComune').val("").change();

        if (selectedValue === "") {
            return;
        }

        $.getJSON('@Url.Action("GetComuni", "RegioneProvinciaComune")', { provinciaId: selectedValue }, function (dati) {
  
            $.each(dati, function (index, item) {
                //console.log(item.Value)
                if (item.text === selectedText) {
                    console.log("TROVATO il comune uguale alla provincia");
                    $('#comboComune').append($('<option />', { value: item.value, text: item.text , selected: true}));
                } else {
                    $('#comboComune').append($('<option />', { value: item.value, text: item.text }));
                }
                
            });
        });

    }

</script>

sito4.0/Views/Shared/_ConfirmDelete.cshtml
@{

    string id = "confirmDelete";
    if (ViewData["ID"] != null)
    {
        id = ViewData["ID"].ToString();
    }


    string title = "Cancellazione";
    if (ViewData["title"] != null)
    {
        title = ViewData["title"].ToString();
    }

}


<div class="modal" tabindex="-1" role="dialog" id="@id">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">@title</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Confermare la cancellazione dell'elemento selezionato?</p>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary"><i class="fa fa-trash fa-fw"></i>Delete</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

sito4.0/Views/Shared/_ConfirmPopup.cshtml
@{

    string id = "confirmPopup";
    if (ViewData["ID"] != null)
    {
        id = ViewData["ID"].ToString();
    }


    string title = "Confermare l'operazione";
    if (ViewData["title"] != null)
    {
        title = ViewData["title"].ToString();
    }


    string body = "Confermare l'operazione?";
    if (ViewData["body"] != null)
    {
        body = ViewData["body"].ToString();
    }



}


<div class="modal" tabindex="-1" role="dialog" id="@id">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">@title</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>@body</p>
            </div>
            <div class="modal-footer">
                <!-- richiamo una funzione con il id -->
                <button type="button" class="btn btn-primary" onclick="@(id + "ConfirmOnClick()")" ><i class="fa fa-fw fa-exclamation "></i>Conferma</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annulla</button>
            </div>
        </div>
    </div>
</div>