sito4.0/Areas/Admin/Controllers/AnnunciController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyWebApplication.Areas.Admin.Controllers
{
    [Authorize]
    public class AnnunciController : MyBaseController
    {
        private Annunci.AnnunciAdminManager manager = new Annunci.AnnunciAdminManager("mercatino");

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Details(MyWebApplication.Areas.Admin.Models.AnnuncioDetailsModel model)
        {

         //   model.annuncioId = 727456154;
            return View(model);
        }



        [HttpPost]
        [ActionName("Details")]
        [ValidateAntiForgeryToken]
        public ActionResult DetailsPost(MyWebApplication.Areas.Admin.Models.AnnuncioDetailsModel model)
        {
            System.Collections.Hashtable hashtableRisposte = new System.Collections.Hashtable();

            manager.mOpenConnection();
            try
            {
                model.annuncio = manager.getAnnuncio(model.annuncioId);

                if (model.annuncio == null)
                {
                   // return HttpNotFound();
                }


                Annunci.AnnunciAdminManager adminManager = new Annunci.AnnunciAdminManager(manager.mGetConnection());

                model.trattative = adminManager.getTrattativeByAnnuncio(model.annuncioId, Annunci.Models.Trattativa.TipoTrattativa.Libro);
                long numeroRisposte;
                foreach (Annunci.Models.Trattativa t in model.trattative)
                {
                    numeroRisposte = manager.getNumeroRisposteOfTrattativa(t.trattativaId, model.annuncio.userId);
                    hashtableRisposte.Add(t.trattativaId, numeroRisposte);
                }

                // PHOTO
                Annunci.PhotoManager photoManager = new Annunci.PhotoManager(manager.mGetConnection());

                //List<Annunci.Models.MyPhoto> photos;
                //photos = photoManager.getMyPhotosIsNotPlanimetria(id);

                // Debug.WriteLine("Trovate {0} immagini", photos.Count);



                //  model.photos = photos;
            }
            finally
            {
                manager.mCloseConnection();
            }

            ViewData["hashtableRisposte"] = hashtableRisposte;
            return View(model);
        }


        

        public ActionResult Trattativa(long? id)
        {
            TempData["AREA"] = "Admin";

            MyWebApplication.Controllers.LibriController  controller = new MyWebApplication.Controllers.LibriController();
            controller.ControllerContext = ControllerContext;
            controller.TempData = TempData;
            return controller.Trattativa(id);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteAnnuncio(long? id)
        {
            //CANCELLAZIONE FISICA
            if (id == null)
            {
                return HttpNotFound();
            }

            bool esito;
            manager.mOpenConnection();
            try
            {
                esito = manager.deleteAnnuncio((long)id, Server.MapPath("~"));
            }
            finally
            {
                manager.mCloseConnection();
            }

            return RedirectToAction("Details");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteAnnuncioLogic(long? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            bool esito;
            manager.mOpenConnection();
            try
            {
                esito = manager.deleteAnnuncioLogic((long)id, Annunci.AnnunciManager.StatoAnnuncio.Da_cancellare, Server.MapPath("~"));
            }
            finally
            {
                manager.mCloseConnection();
            }

            return RedirectToAction("Details");
        }


    }
}

sito4.0/Controllers/LibriController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Web;
using System.Web.Mvc;

namespace MyWebApplication.Controllers
{
    [Authorize]
    public class LibriController : MyBaseController
    {


        public const int MaxWidthImage = 500;
        public const int MaxHeightImage = 500;

        public const int WidthThumbnail = 200;
        public const int HeightThumbnail = 200;

        private const string SESSSION_FILTER_SEARCH = "SearchLibriModel";

        private Annunci.Libri.LibriManager manager = new Annunci.Libri.LibriManager("mercatino");

        private MyManagerCSharp.RegioniProvinceComuniManager regioniProvinceComuniManager = new MyManagerCSharp.RegioniProvinceComuniManager("RegioniProvinceComuni");


        [AllowAnonymous]
        public ActionResult Index(Annunci.Libri.Models.SearchLibri model)
        {
            Debug.WriteLine("HttpMethod: " + (Request.HttpMethod == null ? "NULL" : Request.HttpMethod.ToString()));
            Debug.WriteLine("UrlReferrer: " + (Request.UrlReferrer == null || Request.UrlReferrer.LocalPath == null ? "NULL" : Request.UrlReferrer.LocalPath));

            if (Request.HttpMethod.ToString() == "GET" && Session[SESSSION_FILTER_SEARCH] != null && Request.UrlReferrer != null
                && Request.UrlReferrer.LocalPath.IndexOf("/Libri/TestiScolastici") == -1
                //&& Request.UrlReferrer.LocalPath.IndexOf("/Libri/Details") == -1
                && Request.UrlReferrer.LocalPath != "/Libri/Categorie")
            {
                model = (Session[SESSSION_FILTER_SEARCH] as Annunci.Libri.Models.SearchLibri);
                //model.filter = (Session[SESSSION_FILTER_SEARCH] as Annunci.Libri.Models.Libro);
                Debug.WriteLine("Leggo i parametri di ricerca dalla sessione ...");
                Debug.WriteLine("Filtro Days: " + model.days);
            }

            if (model.filter == null)
            {
                model.filter = new Annunci.Libri.Models.Libro();
            }
            Debug.WriteLine("collapseShow: " + model.collapseShow);
            Debug.WriteLine("CategoriaId: " + model.filter.categoriaId);
            Debug.WriteLine("SubCategoriaId: " + model.filter.subCategoriaId);

            System.Collections.Hashtable hashtablePhoto = new System.Collections.Hashtable();
            try
            {
                manager.mOpenConnection();

                model.comboCategorie = manager.getComboCategoria(1000000);
                if (model.filter.categoriaId != null &&
                    ((model.filter.categoriaId >= 1130000 && model.filter.categoriaId < 1140000) || (model.filter.categoriaId >= 1140000 && model.filter.categoriaId < 1150000)))
                {
                    model.comboSubCategorie = manager.getComboCategoria((int)model.filter.categoriaId);
                }

                model.comboRegioni = regioniProvinceComuniManager.getComboRegioni();
                if (model.filter.regioneId != null)
                {
                    model.comboProvince = regioniProvinceComuniManager.getComboProvince((int)model.filter.regioneId);
                }

                if (model.filter.provinciaId != null)
                {
                    model.comboComuni = regioniProvinceComuniManager.getComboComuni(model.filter.provinciaId);
                }

                manager.getList(model);


                long numeroPhoto;
                foreach (Annunci.Libri.Models.Libro i in model.Libri)
                {
                    numeroPhoto = manager.countPhoto(i.annuncioId);
                    hashtablePhoto.Add(i.annuncioId, numeroPhoto);
                }


                if (model.filter.categoriaId == 1130000 && model.filter.subCategoriaId == null)
                {
                    model.filter.categoria = "Testi scolastici";
                }

                if (model.filter.categoriaId == 1140000 && model.filter.subCategoriaId == null)
                {
                    model.filter.categoria = "Testi universitari";
                }

                /* 
                 //gestione nome categoria 
                 switch (model.filter.subCategoriaId)
                 {
                     case 1130100:
                         model.filter.categoria = "Testi scolastici elemetari";
                         break;
                     case 1130200:
                         model.filter.categoria = "Testi scolastici medie";
                         break;
                     case 1130300:
                         model.filter.categoria = "Testi scolastici superiori";
                         break;
                     case 1130400:
                         model.filter.categoria = "Testi scolastici altro";
                         break;
                 }

     */

            }
            finally
            {
                manager.mCloseConnection();
            }

            Session[SESSSION_FILTER_SEARCH] = model;
            ViewData["hashtablePhoto"] = hashtablePhoto;
            return View("Index", model);
        }


        [AllowAnonymous]
        public ActionResult Categorie()
        {
            return View();
        }


        [AllowAnonymous]
        public ActionResult Categoria(int? id)
        {
            Debug.WriteLine("HttpMethod: " + (Request.HttpMethod == null ? "NULL" : Request.HttpMethod.ToString()));
            Debug.WriteLine("UrlReferrer: " + (Request.UrlReferrer == null || Request.UrlReferrer.LocalPath == null ? "NULL" : Request.UrlReferrer.LocalPath));
            Debug.WriteLine("Categoria: " + id);

            Annunci.Libri.Models.SearchLibri model;
            model = (Session[SESSSION_FILTER_SEARCH] as Annunci.Libri.Models.SearchLibri);
            if (model == null)
            {
                model = new Annunci.Libri.Models.SearchLibri();
            }

            if (id != -1)
            {
                model.filter.categoriaId = id;

                if (id >= 1130000 && id < 1140000)
                {
                    model.filter.categoriaId = 1130000;
                    model.filter.subCategoriaId = id;
                }

                if (id >= 1140000 && id < 1150000)
                {
                    model.filter.categoriaId = 1140000;
                    model.filter.subCategoriaId = id;

                }
                /* rimosso nella rel.  3.0.0.8 - 30/04/2018
                if (Request.Browser.Browser.Contains("AdsBot-Google") || Request.Browser.Browser.Contains("Googlebot"))
                {
                    model.PageSize = 0;
                    model.PageNumber = 1;
                }
                */
            }
            Session[SESSSION_FILTER_SEARCH] = model;

            //return RedirectToAction("Index", model);
            return Index(model);
        }



        public ActionResult MyAnnunci(Annunci.Libri.Models.SearchLibri model)
        {
            System.Collections.Hashtable hashtableRisposte = new System.Collections.Hashtable();
            try
            {
                manager.mOpenConnection();

                manager.getMyListAnnunci(MySessionData.UserId, model);

                Annunci.AnnunciManager annuncioManager = new Annunci.AnnunciManager(manager.mGetConnection());
                long numeroRisposte;
                foreach (Annunci.Libri.Models.Libro i in model.Libri)
                {
                    numeroRisposte = annuncioManager.getNumeroRisposteOfAnnuncio(i.annuncioId, MySessionData.UserId);
                    hashtableRisposte.Add(i.annuncioId, numeroRisposte);
                }
            }
            finally
            {
                manager.mCloseConnection();
            }

            ViewData["hashtableRisposte"] = hashtableRisposte;
            return View(model);
        }

        public ActionResult MyTrattative()
        {
            manager.mOpenConnection();

            List<Annunci.Models.Trattativa> risultato;

            try
            {
                risultato = manager.getListTrattative(MySessionData.UserId, Annunci.Models.Trattativa.TipoTrattativa.Libro);
            }
            finally
            {
                manager.mCloseConnection();
            }


            return View(risultato);
        }


        [Authorize]
        public ActionResult Trattativa(long? id)
        {
            Debug.WriteLine("trattativaId: " + id);
            Models.ModelTrattativa model = new Models.ModelTrattativa();

            manager.mOpenConnection();
            try
            {
                //La coppa trattativaID e annuncioID sono + sicuri per leggere gli annunci
                //if (annuncioId == null) {
                //  annuncioId = manager.getAnnucioIdFromTrattativa((long)trattativaId);
                //}

                model.trattativa = manager.getTrattativa((long)id);
                if (model.trattativa == null)
                {
                    return View("~/Views/Errors/NotAvailable.cshtml");
                }

                if (!manager.authorizeShowTrattativa(MySessionData.UserId, (long)id))
                {
                    return RedirectToAction("NotAuthorized", "Errors");
                }


                manager.setRisposteFromTrattativa(model.trattativa);


                model.libro = manager.getLibro(model.trattativa.annuncioId);
                if (model.libro == null)
                {
                    //vuol dire che l'annuncio è stato rimosso ... 
                    //return View("NotAvailable");

                    // il controllo lo faccio sulla VIEW così visualizzo i pulsanti corretti
                }


                //Verifico se l'utente che ha inserito la risposta sia il prorietario dell'annuncio
                bool isOwner;
                isOwner = manager.isOwner(model.trattativa.annuncioId, MySessionData.UserId);

                if (isOwner)
                {

sito4.0/Areas/Admin/Views/Annunci/Details.cshtml
@model  MyWebApplication.Areas.Admin.Models.AnnuncioDetailsModel
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/MasterPageAdmin.cshtml";
}

<h2>Details</h2>

@using (Html.BeginForm("Details", "Annunci", FormMethod.Post, new { id = "MyForm" }))
{
    @Html.AntiForgeryToken()
    <input class="form-control" placeholder="Inserisci l'ID dell'annuncio" type="text" name="annuncioId" id="annuncioId" value="@Model.annuncioId">
    <button type="submit">Ricerca</button>
}

<hr />


<div class="d-inline-flex">
    @using (Html.BeginForm("DeleteAnnuncio", "Annunci", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <input type="hidden" name="id" value="@Model.annuncioId" />

        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#confirmDelete01">Cancellazione FISICA</button>
        { Html.RenderPartial("_ConfirmDelete", new ViewDataDictionary { { "ID", "confirmDelete01" }, { "title", "Cancellazione FISICA" } }); }
    }

</div>

<div class="d-inline-flex">
    @using (Html.BeginForm("DeleteAnnuncioLocic", "Annunci", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <input type="hidden" name="id" value="@Model.annuncioId" />
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#confirmDelete02">Cancellazione LOGICA</button>
        { Html.RenderPartial("_ConfirmDelete", new ViewDataDictionary { { "ID", "confirmDelete02" }, { "title", "Cancellazione LOGICA" } }); }
    }
</div>



@if (Model.annuncio == null)
{
    <h3>Annuncio is null</h3>
}
else
{
    Html.RenderPartial("_tabellaAnnuncio", Model.annuncio);
}



@{Html.RenderPartial("~/Views/Libri/_TabellaTrattative.cshtml", Model.trattative);}

sito4.0/Areas/Admin/Views/Annunci/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/MasterPageAdmin.cshtml";
}

<h2>Index</h2>



<a href="@Url.Action("Details")" >Dettagli su un annuncio</a>

sito4.0/Areas/Admin/Views/Annunci/Trattativa.cshtml
@model MyWebApplication.Models.ModelTrattativa
@{
    ViewBag.Title = "Trattativa";
    Layout = "~/Areas/Admin/Views/Shared/MasterPageAdmin.cshtml";
}


@if (Model.libro == null)
{
    //vuol dire che l'annuncio è stato rimosso
    <h2>Spiacenti ma l'annucio richiesto non è più disponibile</h2>
    <center>
        <img src="@Url.Content("~/Content/Images/Shared/error.png")" border="0" alt="Failed" style="margin-top:1em;margin-left:1em;" />
    </center>

}
else
{



    <h2>Trattativa</h2>

    { Html.RenderPartial("~/Views/Libri/_TabInfoLibro.cshtml", Model.libro); }

    <br />

    <div id="MyTrattativa">

        @foreach (Annunci.Models.Risposta r in Model.trattativa.risposte)
        {
            <div class="card mb-3 ">
                <div class="card-header bg-success">
                    <span class="MyReplyId">@((r.refRispostaId == -1) ? "" : r.refRispostaId.ToString())</span>
                    <span class="MyDate">@r.dateAdded.ToString()</span>
                </div>

                <div class="card-body">
                    <div class="row">
                        <div class="col-3">
                            <h6>Utente: @r.login</h6>
                            @MyHelper.getProfileImage(Server.MapPath("~"), r.login, r.customerId)
                        </div>

                        <div class="col-9">
                            <div class="row float-right">
                                <a role="button" class="btn btn-primary btn-sm float-right" href="@Url.Action("Reply", "Libri", new { annuncioId = r.annuncioId, trattativaId = r.trattativaId, rispostaId = r.rispostaId })">Reply<i class="fas fa-reply fa-fw"></i></a>
                                &nbsp;
                                <a role="button" class="btn btn-primary btn-sm" href="@Url.Action("Reply", "Libri", new { annuncioId = r.annuncioId, trattativaId = r.trattativaId, quote = r.rispostaId })">Quote<i class="fas fa-quote-right fa-fw"></i></a>
                            </div>

                            <div style="clear:both"></div>

                            <div class="row float-none">
                                <blockquote>@Html.Raw(r.testo)</blockquote>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>


    <a class="btn btn-secondary" href="@(Url.Action("Details")+ "/" + Model.libro.annuncioId)">Torna all'annuncio</a>





}
<a class="btn btn-secondary" href="@Url.Action("MyTrattative")">Torna all'elenco delle trattative</a>

sito4.0/Areas/Admin/Views/Annunci/_tabellaAnnuncio.cshtml
@model Annunci.Models.Annuncio


@if (Model == null)
{
    <h3>Annuncio is NULL</h3>
}
else
{

    <dl class="row">
        <dt class="col-sm-3 col-6">Data inserimento</dt>
        <dd class="col-sm-3 col-6">@Model.dataInserimento.ToString()</dd>
        <dt class="col-sm-3 col-6">Data cancellazione</dt>
        <dd class="col-sm-3 col-6">@MyHelper.decodeNull(Model.dateDeleted)</dd>


        <dt class="col-sm-3 col-6">Utente</dt>
        <dd class="col-sm-3 col-6">@Model.login</dd>


        <dt class="col-sm-3 col-6">Tipo annuncio</dt>
        <dd class="col-sm-3 col-6">@Model.tipo</dd>
        <dt class="col-sm-3 col-6">Categoria</dt>
        <dd class="col-sm-3 col-6">@Model.categoria</dd>


        <dt class="col-sm-3 col-6">Nome</dt>
        <dd class="col-sm-3 col-6">@Model.nome</dd>
        <dt class="col-sm-3 col-6">sss</dt>
        <dd class="col-sm-3 col-6"></dd>


        <dt class="col-sm-3 col-6">Prezzo</dt>
        <dd class="col-sm-3 col-6">@Model.prezzo.ToString("C")</dd>
        <dt class="col-sm-3 col-6">Regione</dt>
        <dd class="col-sm-3 col-6">@MyHelper.decodeNull(Model.regione)</dd>

        <dt class="col-sm-3 col-6">Provincia</dt>
        <dd class="col-sm-3 col-6">@MyHelper.decodeNull(Model.provincia)</dd>
        <dt class="col-sm-3 col-6">Comune</dt>
        <dd class="col-sm-3 col-6">@MyHelper.decodeNull(Model.comune)</dd>

    </dl>



}